"""second migration

Revision ID: 58f4c3e33cd4
Revises: 8d6740d2bc78
Create Date: 2024-10-29 10:55:04.609336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f4c3e33cd4'
down_revision: Union[str, None] = '8d6740d2bc78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_name', sa.String(), nullable=False))
    op.create_foreign_key(None, 'posts', 'users', ['user_name'], ['user_name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_name')
    # ### end Alembic commands ###
